### ISSUE TITLE
Unsupported major.minor version 52.0 [Plugin: net.orekyuu.bitbucketissues]

### ISSUE THREAD

**Issue by iNdieboyjeff** [orekyuu/BitbucketIssueViewer#1]
Installed on Android Studio and get this error:

4:56:02 PluginException: net/orekyuu/bitbucketissues/IssueViewFactory : Unsupported major.minor version 52.0 [Plugin: net.orekyuu.bitbucketissues]
14:56:07 PluginException: net/orekyuu/bitbucketissues/IssueViewFactory : Unsupported major.minor version 52.0 [Plugin: net.orekyuu.bitbucketissues]

**Comment by orekyuu** [comment]
@iNdieboyjeff Could you please tell me your java runtime version?

**Comment by iNdieboyjeff** [comment]
![screen shot 2015-07-22 at 16 01 44](https://cloud.githubusercontent.com/assets/851270/8828606/fb36d90c-308a-11e5-874c-6d3c822cc1d9.png)

**Comment by orekyuu** [comment]
Please update the java runtime to 1.8.

**Comment by iNdieboyjeff** [comment]
It would be helpful if you could make the plugin work with Java 1.6.  Users should not need to change their version of Java just for a single plugin.

**Comment by orekyuu** [comment]
I agree. I will do the work in the near future.

**Comment by orekyuu** [comment]
#2
